language: java
jdk:
  - oraclejdk8

notifications:
  slack:
    rooms:
      - pictopage:GgJNEnLcl4annmdzEwdCVbqY#random

script: "./gradlew test"

after_success:
  - bash <(curl -s https://codecov.io/bash)
