apply plugin: 'java'

group = 'com.artemas'
version = '1.1-SNAPSHOT'

description = "Codewars Kata Challenges"

sourceCompatibility = JavaVersion.VERSION_11
targetCompatibility = JavaVersion.VERSION_11



repositories {
    mavenCentral()
}
dependencies {
    testImplementation 'org.testng:testng:7.7.0'
    testImplementation("org.hamcrest:hamcrest:2.2")
    testImplementation('org.junit.jupiter:junit-jupiter-api:5.3.2')
    testImplementation('org.junit.jupiter:junit-jupiter-params:5.3.2')
    testImplementation('org.junit.jupiter:junit-jupiter-engine:5.3.2')
    testImplementation('org.assertj:assertj-core:3.11.1')
    implementation 'org.projectlombok:lombok:1.18.10'
    annotationProcessor 'org.projectlombok:lombok:1.18.10'
    implementation group: 'org.apache.commons', name: 'commons-lang3', version: '3.18.0'
}

test {
    useJUnitPlatform()
    testLogging {
        events = ["FAILED", "SKIPPED"]
    }
}
